<?php

namespace App\Repos;

class PelanggaranRepos extends BaseRepos
{

    public function __construct($model)
    {
        $this->model = $model;
    }
    public function getAllDataByNISN($id)
    {
        return parent::getAllData()->where('NISN', $id); // TODO: Change the autogenerated stub
    }
    public function getAllDataByYear($year)
    {
        return $this->model->whereYear('tanggal_pelanggaran', $year)->get();
    }
    public function getALlDataByMonth($month)
    {
        return $this->model->whereMonth('tanggal_pelanggaran', $month)->get();
    }
    public function getAllDataByDay($day)
    {
        return $this->model->whereDay('tanggal_pelanggaran', $day)->get();
    }
    public function getAllDataBySemester($semester)
    {
        $nisn = auth()->guard('siswa')->user()->NISN;
        return parent::getAllData()->where('NISN', $nisn)->where('semester', $semester);
    }
}
