<?php

namespace App\Repos;

class PelanggaranRepos extends BaseRepos
{

    public function __construct($model)
    {
        $this->model = $model;
    }

    public function getAllDataByNISN($id)
    {
        return parent::getAllData()->where('NISN', $id); // TODO: Change the autogenerated stub
    }

}
